[[redirects]]
  force = true
  from = "/scripts/x.js"
  status = 200
  to = "https://painelalentoapi.up.railway.app/"

[[headers]]
for = "/*" # you can configure the correct paths here
[headers.values]
  access-control-allow-origin = *